[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["./node_modules/.bin/tsc -b && ./node_modules/.bin/vite build"]

[start]
cmd = "npm start"
